### ISSUE TITLE
WezTerm Dark Colors Off

### ISSUE THREAD

**Issue by HeyItsGilbert** [kepano/flexoki#37]
The current wezterm dark seems like the colors are off.  

## Current
![Screenshot 2023-10-11 190604](https://github.com/kepano/flexoki/assets/615265/a5c6dd10-d7d4-492c-9057-e7b336cdc2c1)

## After
![image](https://github.com/kepano/flexoki/assets/615265/27d16469-d36b-4902-8e2b-1cbca21a9f7a)

**Comment by kepano** [comment]
@jbromley can you take a look?

**Comment by kepano** [comment]
I see what you mean @HeyItsGilbert — some of these are somewhat up to personal preference but I agree that the defined colors seemed wrong and new ones look better

Questions marks for me:

- Should Magenta use Flexoki magenta? Purple is also okay since it seems like WezTerm doesn't have a purple or violet
- Error Accent is set to cyan?

**Comment by kepano** [comment]
I'll merge since it seems like a net improvement and we can refine based on feedback.

**Comment by HeyItsGilbert** [comment]
You know I was on the fence about magenta. I was reading up on the ascii base 8 colors and "magenta" options always looks more purple then magenta. I'm happy to make the edit though.

**Comment by kepano** [comment]
I think your choice might be best because it provides a bit more color separation compared to red.
