### ISSUE TITLE
Improvements to the Neovim port

### ISSUE THREAD

**Issue by polak-jan** [kepano/flexoki#48]
Sadly right now I would describe the Neovim port as just barely usable. It doesn't really adapt well to different configs, for example the author is obviously using borders on floating windows, as without them the window just blends with the regular background.
![image](https://github.com/kepano/flexoki/assets/11616898/31d06032-848d-459d-bad3-0cea399c95a4)

This issue should ideally become a tracking one for all fixes needed on the port, while they get fixed in batches.

Personally I would ideally want to see some way to configure the there. With the floating windows being a really good example of why. Different behavious being desirable based on the existence of the border. Maybe this could be automatically detected, with an option for a manual override in the setup function.

Here is a list of issues I have encountered so far:
- [ ] Floatings windows blend into background without borders
- [ ] GoLang type definitions using blue for all tokens
- [ ] Installation instructions point to a wrong repository
- [ ] Use of external dependancy to generate the source files (see bellow)

And missing support for plugins, personally I have encountered the following:
- [ ] NeoTree
- [ ] flash-nvim

(tagging the people that commited to the Neovim port so far: @stevedylandev @eltociear @dinocosta)

**Comment by polak-jan** [comment]
Looking at the recent commits, I also don't really understand the need for the external dependency. The input TOML files are really close to its output, providing only marginal benefits, while limiting the theme to being a simple static file, removing all the benefits of it being a Lua script.

**Comment by dinocosta** [comment]
Thank you for creating this issue @polak-jan 👍 

Could you update the list of issues to include updating the installation instructions so as to point to this repository? It's currently telling users to install the plugin at [stevedylandev/flexoki-nvim](https://github.com/stevedylandev/flexoki-nvim) , so any changes we do here won't reflect in user's installations unless they're actually pointing to this repository.

Also, I'm not sure if current package managers for Neovim support installing plugins located in a specific folder in a repository, instead of the root level, at least I wasn't able to do so with [lazy.nvim](https://github.com/folke/lazy.nvim). We might want to follow the approach of [catppuccin/nvim](https://github.com/catppuccin/nvim) and [rose-pine/neovim](https://github.com/rose-pine/neovim), and ask @kepano to create a separate repository just for the neovim colorscheme, maybe something like `kepano/flexoki.nvim`. What do you think @stevedylandev @eltociear @polak-jan ?

> Looking at the recent commits, I also don't really understand the need for the external dependency. The input TOML files are really close to its output, providing only marginal benefits, while limiting the theme to being a simple static file, removing all the benefits of it being a Lua script.

Not the original plugin writer but I suspect [colorgen-nvim](https://github.com/LunarVim/colorgen-nvim) was simply used because it was quicker to generate a color scheme from a single TOML file, instead of having to write one from scratch. Personally I'm ok with revisiting this approach, especially because, as I've shared in [this PR](https://github.com/kepano/flexoki/pull/47), I suspect [colorgen-nvim](https://github.com/LunarVim/colorgen-nvim)
 does not support multiple variants from the same palette, so we'd probably end up with a TOML file for the dark version and one for the light version.

**Comment by polak-jan** [comment]
Yeah, the install instructions did seem weird but I just assumed it somehow resolved to this repo for some reason.

As for it being in a subdirectory. As far as I know, while we could make it work, it would mean that the entire repo would be downloaded, not just the nvim part, which isn't ideal.

**Comment by kepano** [comment]
I'm okay with Neovim being split into its own repo if that helps.

**Comment by polak-jan** [comment]
Yeah, that's basically a hard requirment. So if you could please create it, we will sort out the rest.

**Comment by fceruti** [comment]
I would also add the possibility to change the background. 
I believe the first 3 or 4 grays  in the original flexoki image (from left to right) would all be a good fit to use as background. 
The one that's used now, is too high contrast for my taste.

**Comment by polak-jan** [comment]
We are still waiting for @kepano to create the separate repository as without that the scheme can't actually be installed. Or would you be fine with the "official" repo being hosted outside your account?

**Comment by kepano** [comment]
@polak-jan Oops! I have created the repo here:
https://github.com/kepano/flexoki-neovim

Also added @dinocosta as a collaborator to help approve PRs since I don't use Neovim myself

**Comment by polak-jan** [comment]
Thank you, we will get started than!
